using System;

namespace CloudFoundryServiceBroker.Interfaces.Entities
{
    /// <summary>
    /// Binding request details
    /// </summary>
    public class CreateBindingRequest
    {
        /// <summary>
        /// Service instance id
        /// </summary>
        /// <remarks>Service instance is generated by Cloud Foundry and will be used with all requests to the service</remarks>
        public string ServiceInstanceId { get; set; }
        /// <summary>
        /// Binding instance id
        /// </summary>
        public string BindingInstanceId { get; set; }

        /// <summary>
        /// Service type Id
        /// </summary>
        /// <remarks>Unique identifier that identify service type</remarks>
        public Guid ServiceTypeId { get; set; }
        /// <summary>
        /// Plan Id
        /// </summary>
        public Guid PlanId { get; set; }
        /// <summary>
        /// Application Id
        /// </summary>
        public Guid ApplicationId { get; set; }
    }
}
